services:
  api:
    build: .
    container_name: ml-hub-api
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - ML_APP_ID=${ML_APP_ID}
      - ML_CLIENT_SECRET=${ML_CLIENT_SECRET}
      - ML_REDIRECT_URI=${ML_REDIRECT_URI}
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped
